// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIJUWUz7ywkdTrU1KmM-okzKT_uLVo_qM',
    appId: '1:82430019843:web:15699659bf18c123120136',
    messagingSenderId: '82430019843',
    projectId: 'medical-6bc78',
    authDomain: 'medical-6bc78.firebaseapp.com',
    storageBucket: 'medical-6bc78.appspot.com',
    measurementId: 'G-9NV3MTYNWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWgjAEtUtPkt-dIKqye1Itq8fbgkdNawo',
    appId: '1:82430019843:android:58a2be3b73e86371120136',
    messagingSenderId: '82430019843',
    projectId: 'medical-6bc78',
    storageBucket: 'medical-6bc78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJFEF0MAvlcdMwp_sw7teZ0-3yu-ArCjw',
    appId: '1:82430019843:ios:3562ef9741388cc0120136',
    messagingSenderId: '82430019843',
    projectId: 'medical-6bc78',
    storageBucket: 'medical-6bc78.appspot.com',
    iosClientId: '82430019843-7j5ga5n5b2p5r3jvh5p9158ag2l37m37.apps.googleusercontent.com',
    iosBundleId: 'com.example.med',
  );
}
